const express = require('express');
const cheerio = require('cheerio');
const app = express();
const PORT = process.env.PORT || 3000;
const KEY = process.env.TMDB_API_KEY;
const MANIFEST={id:'com.italyreleasechecker.nuvio',version:'1.5.0',name:'🇮🇹 Italy Release Checker',description:'Controlla se un film risulta uscito in Italia.',resources:['catalog','meta'],types:['movie'],catalogs:[{type:'movie',id:'italy-release-check',name:'🇮🇹 Italy Release Checker',extra:[]}]};
app.get('/',(q,r)=>r.json({name:MANIFEST.name,version:MANIFEST.version,status:'ok'}));
app.get('/manifest.json',(q,r)=>r.json(MANIFEST));
async function tmdb(path){if(!KEY)return null;const u=new URL('https://api.themoviedb.org/3'+path);u.searchParams.set('api_key',KEY);u.searchParams.set('language','it-IT');const r=await fetch(u);return r.ok?r.json():null}
async function tmdbIT(id){const d=await tmdb('/movie/'+id+'/release_dates');const it=(d?.results||[]).find(x=>x.iso_3166_1==='IT');return !!it?.release_dates?.some(x=>x.release_date&&[1,2,3,4,5,6].includes(x.type))}
async function imdbIT(imdb){if(!imdb)return false;try{const r=await fetch('https://www.imdb.com/title/'+imdb+'/releaseinfo/',{headers:{'accept':'text/html','accept-language':'it-IT,it;q=0.9','user-agent':'Mozilla/5.0'} });if(!r.ok)return false;const $=cheerio.load(await r.text());const t=$('body').text().replace(/\s+/g,' ');return /\bItaly\b/i.test(t)||/\bItalia\b/i.test(t)}catch{return false}}
async function wikidataIT(id){const m=await tmdb('/movie/'+id);if(!m)return false;const imdb=m.imdb_id;if(!imdb)return false;try{const q=`SELECT ?place WHERE {?item wdt:P345 "${imdb}". ?item p:P577 ?st. ?st pq:P291 ?place.} LIMIT 50`;const r=await fetch('https://query.wikidata.org/sparql?format=json&query='+encodeURIComponent(q),{headers:{'accept':'application/sparql-results+json','user-agent':'ItalyReleaseChecker/1.5'}});if(!r.ok)return false;for(const x of (await r.json()).results?.bindings||[]){const p=x.place?.value?.split('/').pop();if(p==='Q38')return true;if(/^Q\d+$/.test(p)){const q2=`ASK { wd:${p} (wdt:P17|wdt:P131)* wd:Q38 }`;const rr=await fetch('https://query.wikidata.org/sparql?format=json&query='+encodeURIComponent(q2),{headers:{'accept':'application/sparql-results+json','user-agent':'ItalyReleaseChecker/1.5'}});if(rr.ok&&(await rr.json()).boolean)return true}}}catch{}return false}
async function justwatch(title){if(!title)return false;try{const r=await fetch('https://www.justwatch.com/it/ricerca?q='+encodeURIComponent(title),{headers:{'accept':'text/html','accept-language':'it-IT,it;q=0.9','user-agent':'Mozilla/5.0'}});if(!r.ok)return false;const $=cheerio.load(await r.text());const n=s=>String(s||'').toLowerCase().replace(/[^\p{L}\p{N}]+/gu,' ').trim();const w=n(title);let ok=false;$('a').each((_,e)=>{const t=n($(e).text());if(t&&t===w)ok=true});return ok}catch{return false}}
async function wikipedia(title){try{const u='https://it.wikipedia.org/w/api.php?action=query&format=json&prop=extracts&explaintext=1&redirects=1&titles='+encodeURIComponent(title);const r=await fetch(u,{headers:{'user-agent':'ItalyReleaseChecker/1.5'}});if(!r.ok)return false;const d=await r.json();const p=Object.values(d.query?.pages||{})[0];const t=p?.extract||'';return /(?:uscita|distribuzione|distribuito|distribuita|pubblicato|pubblicata)[\s\S]{0,500}\bItalia\b/i.test(t)||/\bItalia\b[\s\S]{0,500}(?:uscita|distribuzione|distribuito|distribuita)/i.test(t)}catch{return false}}
app.get('/meta/movie/:id.json',async(req,res)=>{try{const id=req.params.id.replace(/^tmdb:/,'');if(!/^\d+$/.test(id))return res.status(400).json({error:'Use a TMDB movie id'});const m=await tmdb('/movie/'+id);if(!m)return res.status(404).json({error:'Movie not found'});const [a,b,c,d]=await Promise.allSettled([tmdbIT(id),imdbIT(m.imdb_id),wikidataIT(id),justwatch(m.title||m.original_title)]);const released=[a,b,c,d].some(x=>x.status==='fulfilled'&&x.value===true);res.json({meta:{id:'tmdb:'+id,type:'movie',name:m.title||m.original_title,poster:m.poster_path?'https://image.tmdb.org/t/p/w500'+m.poster_path:undefined,description:released?'🇮🇹 USCITO IN ITALIA':'🚫 NON USCITO IN ITALIA'}})}catch(e){res.status(500).json({error:'Release check failed'})}});
app.get('/catalog/movie/italy-release-check.json',(q,r)=>r.json({metas:[]}));
app.listen(PORT,()=>console.log('Italy Release Checker 1.5 listening on '+PORT));
