import express from 'express';
const app=express(); const PORT=process.env.PORT||3000; const KEY=process.env.TMDB_API_KEY;
const BASE='https://api.themoviedb.org/3'; const IMG='https://image.tmdb.org/t/p/w500';
async function tmdb(path,params={}){if(!KEY)throw Error('TMDB_API_KEY missing');const u=new URL(BASE+path);u.searchParams.set('api_key',KEY);for(const[k,v]of Object.entries(params))if(v!=null)u.searchParams.set(k,v);const r=await fetch(u);if(!r.ok)throw Error('TMDB HTTP '+r.status);return r.json()}
function itRelease(d){const it=d?.results?.find(x=>x.iso_3166_1==='IT');if(!it?.release_dates?.length)return null;return it.release_dates.filter(x=>x.release_date).sort((a,b)=>a.release_date.localeCompare(b.release_date))[0]||null}
function typeLabel(t){return ({1:'Premiere',2:'Cinema limitato',3:'Cinema',4:'Digitale',5:'Home video',6:'TV'})[t]||'Altro'}
function meta(m,it){const r=it?`🇮🇹 Uscita Italia: ${it.release_date.slice(0,10)} — ${typeLabel(it.type)}`:'🚫 Nessuna uscita italiana registrata su TMDB';return {id:`tmdb:${m.id}`,type:'movie',name:m.title||m.original_title,poster:m.poster_path?IMG+m.poster_path:undefined,background:m.backdrop_path?`https://image.tmdb.org/t/p/w1280${m.backdrop_path}`:undefined,description:`${r}\n\n${m.overview||''}`.trim(),releaseInfo:r,releaseDate:m.release_date||undefined}}
app.get('/manifest.json',(req,res)=>res.json({id:'com.italyreleasechecker.nuvio',version:'1.0.0',name:'🇮🇹 Italy Release Checker',description:'Controlla le date di uscita italiane dei film usando TMDB.',resources:['catalog','meta'],types:['movie'],catalogs:[{type:'movie',id:'no-italy-release',name:'🇮🇹 Non usciti in Italia',extra:[{name:'skip',isRequired:false}]},{type:'movie',id:'italy-release-check',name:'🇮🇹 Cerca release Italia',extra:[{name:'search',isRequired:false}]}]}));
app.get('/catalog/movie/italy-release-check.json',async(req,res)=>{try{const q=String(req.query.search||'').trim();if(!q)return res.json({metas:[]});const d=await tmdb('/search/movie',{query:q,language:'it-IT',include_adult:'false'});const metas=[];for(const m of (d.results||[]).slice(0,10)){try{metas.push(meta(m,itRelease(await tmdb(`/movie/${m.id}/release_dates`))))}catch{}}res.json({metas})}catch(e){res.status(500).json({metas:[],error:e.message})}});
app.get('/catalog/movie/no-italy-release.json',async(req,res)=>{try{const page=Math.max(1,Math.min(Math.floor(Number(req.query.skip||0)/20)+1,500));const d=await tmdb('/discover/movie',{language:'it-IT',sort_by:'popularity.desc',page,include_adult:'false'});const metas=[];for(const m of (d.results||[]).slice(0,20)){try{if(!itRelease(await tmdb(`/movie/${m.id}/release_dates`)))metas.push(meta(m,null))}catch{}}res.json({metas})}catch(e){res.status(500).json({metas:[],error:e.message})}});
app.get('/meta/movie/:id.json',async(req,res)=>{try{const id=req.params.id.replace(/^tmdb:/,'');if(!/^\d+$/.test(id))return res.status(400).json({error:'TMDB ID non valido'});const[m,r]=await Promise.all([tmdb(`/movie/${id}`,{language:'it-IT'}),tmdb(`/movie/${id}/release_dates`)]);res.json({meta:meta(m,itRelease(r))})}catch(e){res.status(500).json({error:e.message})}});
app.get('/',(req,res)=>res.type('text').send('Italy Release Checker\nManifest: /manifest.json\nTMDB key: '+(KEY?'configured':'missing')));app.listen(PORT,()=>console.log('Listening on '+PORT));
